[package]
name = "ggrustlib"
version = "0.1.0"
edition = "2021"

[lib]
name="ggrustlib"

[profile]
dev = { panic = "abort" }
release = { panic = "abort", lto = true, codegen-units = 1, strip = "symbols", opt-level = "s" }

[build-dependencies]
bindgen = "0.63"
regex = "1.5"